### ISSUE TITLE
Update project to angular 14

### ISSUE THREAD

**Issue by juliawaloszek** [Gegelascience/ngx-view360#17]
There is errors in project when run in angular14

```
npm i ngx-view360
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: [project-name]
npm ERR! Found: @angular/common@14.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.1.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"~13.3.0" from ngx-view360@2.2.3
npm ERR! node_modules/ngx-view360
npm ERR!   ngx-view360@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by Gegelascience** [comment]
Thanks for opening this issue.
A new version compatible with v14 is now enabled on npm.
The bug must be fixed with that.

**Comment by juliawaloszek** [comment]
Hi! I still have problem with ngx-view360@2.2.4

I create new project with angular 14 and download package
```
ng new angular-test
npm i ngx-view360  
```

i have in console: 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree       
npm ERR! 
npm ERR! While resolving: angular-test@0.0.0
npm ERR! Found: @angular/common@14.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"~13.3.0" from ngx-view360@2.2.4
npm ERR! node_modules/ngx-view360
npm ERR!   ngx-view360@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Gegelascience** [comment]
Hi, it seems that the cache on my project didn't see the modification of the dependencies for git and npm.

I force the modification and I just publish a 2.2.5.

**Comment by juliawaloszek** [comment]
Hi, 
I just tested it - everything works great. 

Remember to update the documentation.
